{{- if and .Values.api.secrets.create (not .Values.api.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dabir.secretName" . }}
  labels:
    {{- include "dabir.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.api.secrets.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.api.secrets.JWT_SECRET | quote }}
{{- end }}