apiVersion: v2
name: dabir
description: A Helm chart for Dabir letter numbering and registry system
type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - dabir
  - letter-registry
  - golang
  - nextjs

maintainers:
  - name: HajimohammadiNet
    url: https://github.com/hajimohammadinet